version: 2.1

orbs:
  badges: rhems-japan/badges@<<pipeline.parameters.dev-orb-version>>
  # orb-tools: circleci/orb-tools@10.0
  orb-tools: circleci/orb-tools@11.6.1
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0
  rj-badge: rhems-japan/badges@0.0.14


parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
  fingerprint:
    type: string
    default: "a3:d6:d8:63:d8:a8:95:2d:a3:10:31:5e:c7:3d:ed:72"

commands:
  fail-test:
    steps:
      - run:
          name: test error
          command: |
            exit 1

executors:
  cimg_base:
    docker:
      - image: cimg/base:2022.10-20.04


jobs:
  integration-test-1:
    executor: cimg_base
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints:
      #       - << pipeline.parameters.fingerprint >>
      # - fail-test
      - badges/create-badge:
          app: "orbs-badges"
          organization: "orbs-badges"
          color: "pink"
          text: $CIRCLE_BUILD_NUM
          # is_error_text: "failfail"
      - badges/update-readme:
          fingerprint: << pipeline.parameters.fingerprint >>

  integration-test-2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints:
      #       - << pipeline.parameters.fingerprint >>
      - badges/create-badge:
          app: "orbs-badges-2"
          organization: "orbs-badges"
          color: "blue"
          text: $CIRCLE_BUILD_NUM
      - run: sleep 5
      - badges/update-readme:
          fingerprint: << pipeline.parameters.fingerprint >>

  test-badge:
    executor: cimg_base
    steps:
      - checkout
      - rj-badge/create-badge:
          app: "orbs-badges"
          organization: "orbs-badges"
          color: "pink"
          text: $CIRCLE_BUILD_NUM

workflows:
  # test-badge:
  #   jobs:
  #     - test-badge
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      # - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      # - shellcheck/check:
      #     dir: ./src/scripts
      #     exclude: SC2148
      # - bats/run:
      #     path: ./src/tests
      - orb-tools/publish-dev:
          orb-name: rhems-japan/badges
          context: orb-publishing
          requires:
            # - orb-tools/lint
            - orb-tools/pack
            # - bats/run
            # - shellcheck/check
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: rhems-japan/badges
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-1
            # - integration-test-2
          filters:
            branches:
              only:
                - main
