version: 2.1

orbs:
  badges: rhems-japan/badges@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

fil: &fil
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

commands:
  fail-test:
    steps:
      - run:
          name: test error
          command: |
            exit 1

jobs:
  fail-test:
    docker:
      - image: cimg/base:stable
    steps:
      - fail-test
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          # exp. CIRCLE_TAG="alpha/test/v0.0.1"
          name: add scripts
          command: echo ". .circleci/scripts/functions.sh" >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "a3:d6:d8:63:d8:a8:95:2d:a3:10:31:5e:c7:3d:ed:72"
      # - fail-test
      - badges/create-badge:
          app: "orbs-badges"
          organization: "orbs-badges"
          color: "pink"
          text: $CIRCLE_BUILD_NUM
      - badges/update-readme

  integration-test-2:
    working_directory: /tmp/work
    docker:
      - image: rhemsjapan/blue-deploy-deploy:latest
    steps:
      - checkout
      - run:
          name: install sudo & git
          command: |
            apt-get update && apt-get install -y sudo git
            git --version
      - run:
          # exp. CIRCLE_TAG="alpha/test/v0.0.1"
          name: add scripts
          command: echo ". .circleci/scripts/functions.sh" >> $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "a3:d6:d8:63:d8:a8:95:2d:a3:10:31:5e:c7:3d:ed:72"
      # - run: sleep 40
      - badges/create-badge:
          app: "orbs-badges"
          organization: "orbs-badges"
          # color: "#913980"
          # text: $CIRCLE_BUILD_NUM
      - badges/update-readme:
          fingerprint: "a3:d6:d8:63:d8:a8:95:2d:a3:10:31:5e:c7:3d:ed:72"

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      # - orb-tools/lint # Lint Yaml files
      - orb-tools/pack # Pack orb source
      # - shellcheck/check:
      #     dir: ./src/scripts
      #     exclude: SC2148
      - bats/run:
          path: ./src/tests
      - orb-tools/publish-dev:
          orb-name: rhems-japan/badges
          context: orb-publishing
          requires:
            # - orb-tools/lint
            - orb-tools/pack
            - bats/run
            # - shellcheck/check
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # - badges/create_badge:
      #     organization: "orbs-badges"
      # color: "#913980"
      # text: $CIRCLE_BUILD_NUM
      - integration-test-1
      # - integration-test-2
      # - fail-test
      # - badges/update_readme:
      #     only_date: true
      #     branch: hoge
      #     fingerprint: "a3:d6:d8:63:d8:a8:95:2d:a3:10:31:5e:c7:3d:ed:72"
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: rhems-japan/badges
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          # requires:
          #   - integration-test-1
          filters:
            branches:
              only:
                - main

  # integration-test_deploy_2:
  #   when: << pipeline.parameters.run-integration-tests >>
  #   jobs:
  #     - integration-test-2

  test-pack-from-tag:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/pack: # Pack orb source
          <<: *fil
      - bats/run:
          path: ./src/tests
          <<: *fil
      - orb-tools/publish-dev:
          orb-name: rhems-japan/badges
          context: orb-publishing
          requires:
            - orb-tools/pack
            - bats/run
          <<: *fil
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev
          <<: *fil
      - integration-test-1:
          # name: integration-test-from-tag
          requires:
            - orb-tools/publish-dev
          <<: *fil
