version: 2.1
orbs:
  badges: rhems-japan/badges@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.6.1

executors:
  cimg_base:
    docker:
      - image: cimg/base:2022.10-20.04

filters: &filters
  tags:
    only: /.*/

jobs:
  integration-test-1:
    executor: cimg_base
    steps:
      - checkout
      - badges/create-badge:
          app: orbs-badges
          organization: orbs-badges
          color: pink
          text: $CIRCLE_BUILD_NUM
          # is_error_text: "failed"
      - badges/update-readme:
          fingerprint: << pipeline.parameters.fingerprint >>

workflows:
  test-deploy:
    jobs:
      - integration-test-1:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: rhems-japan/badges
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - integration-test-1
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
