description: >
  See the github repository for details on how to use it.

usage:
  version: 2.1
  orbs:
    badges: rhems-japan/badges@x.y.z

commands:
  setup_ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
          - "a0:b1:c2:d3:e4:f5:a6:b7:c8:d9:ea:fb:0c:1d:2e:55"
          
jobs:
  job_name:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_ssh_keys
      - checkout
      - badges/create_badge
      - badges/update_readme